In [110]:
# Import Usual Modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Import modules to make our pipeline
## Preprocessing functions
from sklearn.model_selection import train_test_split
import sklearn.preprocessing as preprocessing
import sklearn.impute as impute
from sklearn.compose import ColumnTransformer

## Pipeline functions
from sklearn.pipeline import Pipeline, FeatureUnion

## Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import cross_validate, GridSearchCV

## Metrics
from sklearn.metrics import roc_curve, confusion_matrix, auc, precision_recall_curve, accuracy_score


#Plotting
import matplotlib.pyplot as plt

#Set output display options
np.set_printoptions(linewidth=132)
np.set_printoptions(precision=4)

In [24]:
# Check credit risk assessment.csv in listdir
os.listdir(".")

['Credit risk assessment.csv',
 '.DS_Store',
 'Untitled.ipynb',
 'config.ipynb',
 '.ipynb_checkpoints',
 'src']

In [51]:
raw_data = pd.read_csv('Credit risk assessment.csv', low_memory = False)

In [43]:
raw_data.shape

(1000, 13)

In [419]:
preds = ['age','gender', 'job_cat', 'housing','savings','checking', 'loan_amount', 'duration','purpose', 'customer_loyalty']
raw_data.dtypes
col_types = {'index':np.int64, 
             'age':np.float64,
             'gender': 'category',
             'job_cat': 'category',
             'housing': 'category',
             'savings': 'category',
             'checking': 'category',
             'loan_amount': np.float64,
             'duration': np.int64,
             'purpose': 'category',
             'risk': 'category',
             'customer_loyalty':np.float64}

In [420]:
raw_data = raw_data.astype(col_types)

In [421]:
# add check for raw_data.dtypes == col_types
raw_data.dtypes

Unnamed: 0             int64
index                  int64
age                  float64
gender              category
job_cat             category
housing             category
savings             category
checking            category
loan_amount          float64
duration               int64
purpose             category
risk                category
customer_loyalty     float64
dtype: object

In [422]:
NAN = [(c, raw_data[c].isna().mean()*100) for c in raw_data]

In [423]:
NAN = pd.DataFrame(NAN, columns = ["column_name", "percentage"])

In [424]:
NAN.sort_values("percentage", ascending = False)

         column_name  percentage
7           checking        39.4
6            savings        18.3
8        loan_amount         4.1
2                age         1.3
0         Unnamed: 0         0.0
1              index         0.0
3             gender         0.0
4            job_cat         0.0
5            housing         0.0
9           duration         0.0
10           purpose         0.0
11              risk         0.0
12  customer_loyalty         0.0

In [425]:
missing_counts = object_cols.isnull().sum()

In [426]:
missing_counts

gender        0
job_cat       0
housing       0
savings     183
checking    394
purpose       0
risk          0
dtype: int64

In [446]:
#split data
X_train, X_test, y_train, y_test = train_test_split(raw_data, raw_data['risk'], test_size = 0.3, random_state = 36)

In [447]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.25, random_state=36)

In [448]:
print(X_train.shape)
print(X_test.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_test.shape)
print(y_valid.shape)

(525, 13)
(300, 13)
(175, 13)
(525,)
(300,)
(175,)

In [449]:
X_object_cols = X_train.select_dtypes(include=['category'])
X_numeric_cols = X_train.drop(object_cols.columns, axis = 1)

In [461]:
preprocessor = ColumnTransformer(
    transformers =[
        ('impute', impute.SimpleImputer(missing_values= np.nan, strategy = 'mean') , list(X_numeric_cols.columns)),
        ('standardize', StandardScaler(), list(X_numeric_cols.columns))
        #('imp_cat', impute.SimpleImputer(strategy = 'most_frequent'), list(X_object_cols.columns)),
        #('ohe', OneHotEncoder(categories = 'auto'), list(X_object_cols.columns))
    ], 
remainder = 'drop', n_jobs = -1)

In [462]:
X_train.dtypes

Unnamed: 0             int64
index                  int64
age                  float64
gender              category
job_cat             category
housing             category
savings             category
checking            category
loan_amount          float64
duration               int64
purpose             category
risk                category
customer_loyalty     float64
dtype: object

In [463]:
preprocessor.fit_transform(X_train)

array([[ 5.5300e+02,  5.5300e+02,  2.7000e+01, ..., -4.8681e-01, -7.2443e-01, -7.3901e-01],
       [ 7.8500e+02,  7.8500e+02,  3.5000e+01, ..., -5.0685e-01, -2.2619e-01,  1.6738e-01],
       [ 3.3500e+02,  3.3500e+02,  4.4000e+01, ...,  2.8760e-02, -1.2227e+00,  7.7251e-01],
       ...,
       [ 1.7200e+02,  1.7200e+02,  3.4000e+01, ..., -4.6120e-01,  2.7206e-01, -4.6447e-02],
       [ 1.2900e+02,  1.2900e+02,  2.9000e+01, ...,  7.1446e-02, -7.2443e-01, -6.7880e-01],
       [ 4.0400e+02,  4.0400e+02,  4.3000e+01, ..., -1.5126e-01, -2.2619e-01,  6.6615e-01]])

In [477]:
cat_imputed = X_object_cols.apply(lambda x:x.fillna(x.value_counts().index[0]))

In [478]:
onehot = OneHotEncoder(sparse = False)

In [479]:
X_cat_1 = onehot.fit_transform(cat_imputed)

In [ ]:
X_train

In [412]:
def rmse(x, y): return math.sqrt(((x-y)**2).mean())

In [413]:
def print_score(mdl):
    res = [rmse(mdl.predict(X_train), y_train),
           rmse(mdl.predict(X_valid), y_valid),
           mdl.score(X_train, y_train), mdl.score(X_valid, y_valid)]
    if hasattr(mdl, 'oob_score_'): res.append(m.oob_score_)
    print(res)

In [415]:
X_train

,Unnamed: 0,index,age,loan_amount,duration,customer_loyalty,gender,job_cat,housing,savings,checking,purpose,risk
553,553,553,27.0,1995.0,12,0.410886,male,2,own,moderate,moderate,car,good
785,785,785,35.0,1941.0,18,0.552889,male,1,own,high,moderate,business,good
335,335,335,44.0,3384.0,6,0.647695,male,3,rent,low,low,furniture/equipment,bad
634,634,634,25.0,1355.0,24,0.363950,female,1,own,low,moderate,car,bad
95,95,95,58.0,15945.0,54,0.844425,male,2,rent,low,moderate,business,bad
301,301,301,42.0,3804.0,36,0.566329,female,2,own,low,moderate,radio/TV,bad
881,881,881,48.0,9277.0,24,0.669453,male,2,free,low,low,car,good
986,986,986,33.0,6289.0,42,0.509578,male,2,own,low,high,business,good
119,119,119,36.0,2366.0,12,0.504766,male,3,own,very_high,moderate,car,good
456,456,456,36.0,3905.0,11,0.497251,male,2,rent,low,low,car,good
277,277,277,49.0,1262.0,12,0.672276,male,1,own,low,low,furniture/equipment,good
555,555,555,22.0,1331.0,12,0.364294,male,2,own,low,moderate,radio/TV,bad
58,58,58,23.0,1961.0,18,0.364105,female,3,own,low,high,car,good
458,458,458,27.0,343.0,6,0.377335,female,2,own,low,low,domestic appliances,good
654,654,654,35.0,2346.0,24,0.556694,male,2,own,low,low,car,good
229,229,229,22.0,3149.0,24,0.341473,male,2,free,low,low,furniture/equipment,good
4,4,4,53.0,4870.0,24,0.786086,male,2,free,low,low,car,bad
64,64,64,26.0,3181.0,24,0.379923,female,2,own,low,low,radio/TV,good
997,997,997,38.0,804.0,12,0.540524,male,2,own,low,low,radio/TV,good
226,226,226,27.0,10961.0,48,0.389270,male,2,own,high,moderate,radio/TV,bad
907,907,907,27.0,3711.0,36,0.417944,male,2,own,low,moderate,education,good
953,953,953,26.0,NaN,36,0.442788,female,3,own,low,low,furniture/equipment,bad
834,834,834,25.0,2327.0,15,0.417403,female,1,own,low,high,radio/TV,bad
299,299,299,32.0,2745.0,21,0.467403,male,2,own,high,moderate,furniture/equipment,good
149,149,149,46.0,1582.0,18,0.696236,male,2,own,high,low,radio/TV,good
63,63,63,25.0,14421.0,48,0.425035,male,2,own,low,moderate,business,bad
469,469,469,35.0,4679.0,24,0.528010,male,1,own,low,low,car,good
18,18,18,44.0,12579.0,24,0.602493,female,3,free,low,moderate,car,bad
87,87,87,47.0,12612.0,36,0.659491,male,2,free,moderate,moderate,education,bad
489,489,489,26.0,3518.0,6,0.383869,unknown,2,rent,low,low,car,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,155,155,20.0,1282.0,12,0.341492,female,2,rent,low,low,furniture/equipment,bad
56,56,56,52.0,6468.0,12,0.770298,male,3,own,low,moderate,radio/TV,bad
150,150,150,42.0,1346.0,6,0.643548,male,2,free,moderate,low,radio/TV,good
874,874,874,29.0,3590.0,12,0.470697,male,1,own,low,low,furniture/equipment,good
439,439,439,26.0,609.0,12,0.424507,female,0,own,low,high,business,bad
181,181,181,30.0,4455.0,36,0.434977,male,3,own,low,moderate,business,bad
202,202,202,26.0,5117.0,27,0.382763,male,2,own,low,low,business,good
924,924,924,55.0,6872.0,24,0.741009,male,2,own,low,low,furniture/equipment,bad
788,788,788,50.0,6224.0,48,0.674883,male,2,free,low,moderate,education,bad
909,909,909,33.0,3195.0,9,0.538887,female,1,own,low,moderate,car,good
167,167,167,20.0,1577.0,11,0.332523,female,2,own,high,moderate,furniture/equipment,good
715,715,715,63.0,7596.0,30,0.865141,male,2,own,low,low,car,good
192,192,192,36.0,3915.0,27,0.529100,male,2,own,low,moderate,business,bad
676,676,676,33.0,NaN,24,0.518267,male,2,own,low,low,furniture/equipment,good
794,794,794,32.0,3062.0,24,0.439334,male,2,rent,very_high,low,furniture/equipment,good
863,863,863,32.0,4526.0,27,0.435331,male,1,own,high,low,furniture/equipment,good
719,719,719,31.0,6148.0,20,0.431356,male,2,own,moderate,moderate,car,good
651,651,651,37.0,1922.0,12,0.546997,male,1,own,low,moderate,furniture/equipment,bad
492,492,492,27.0,1237.0,6,0.361056,female,2,own,moderate,low,radio/TV,good
846,846,846,68.0,6761.0,18,0.967967,male,2,rent,low,low,car,bad
761,761,761,24.0,2124.0,18,0.348348,female,2,rent,low,low,furniture/equipment,bad
101,101,101,24.0,2323.0,36,0.394834,male,2,rent,low,moderate,radio/TV,good
473,473,473,36.0,1238.0,6,0.579642,male,3,own,low,low,education,good
802,802,802,24.0,4272.0,20,0.393189,female,2,own,low,low,furniture/equipment,good
102,102,102,24.0,932.0,6,0.394304,female,2,own,low,low,radio/TV,good
127,127,127,30.0,639.0,12,0.466799,male,2,own,low,moderate,repairs,bad
251,251,251,46.0,2251.0,12,0.680930,female,1,own,low,high,furniture/equipment,good
172,172,172,34.0,2064.0,24,0.519389,female,3,own,low,moderate,furniture/equipment,bad
129,129,129,29.0,3499.0,12,0.420318,female,2,own,low,low,car,bad
404,404,404,43.0,2899.0,18,0.631031,male,2,own,low,moderate,car,good

In [414]:
mdl = RandomForestClassifier(n_jobs = -1)
mdl.fit(X_train, y_train)
#print_score(mdl)

/Users/h391066/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

ValueError: could not convert string to float: 'male'

In [176]:
X_train.dtypes

Unnamed: 0            int64
index                 int64
age                 float64
gender               object
job_cat              object
housing              object
savings              object
checking             object
loan_amount         float64
duration              int64
purpose              object
risk                 object
customer_loyalty    float64
dtype: object

In [178]:
X_train.gender.value_counts()

male       261
female     125
unknown      7
Name: gender, dtype: int64

In [ ]:
#pipe = Pipeline(steps=[('pca', pca), ('logistic', logistic)])

#X_digits, y_digits = datasets.load_digits(return_X_y=True)

# Parameters of pipelines can be set using ‘__’ separated parameter names:
#param_grid = {
    #'pca__n_components': [5, 15, 30, 45, 64],
#    'clf__C': np.logspace(-4, 4, 4)
#}
#search = GridSearchCV(lasso_pipeline, param_grid, n_jobs=-1)
#search.fit(X_train, y_train)